language: python
python:
  - "3.5"
  - "3.6-dev"
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
script:
  - mkdir -p tmp
  - coverage run --source=run.py run.py -l DEBUG -c conf.yaml gen /tmp/test.html
after_success:
  - codeclimate-test-reporter

