os: linux
arch: 
    - amd64
    - arm64
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
script:
  - mkdir -p tmp
  - coverage run --source=generate.py generate.py -l DEBUG -c conf.yaml tmp
after_success:
  - codeclimate-test-reporter

